CP-48444: Fix crash of Python3.6 with "Illegal seek" with --outfd
Python3.6 does not support "ab" if the file is not seekable and
to prevent bugtool to fail in such cases, add a fallback to "wb":

PYTHONPATH=tests/mocks /usr/bin/python3 ./xen-bugtool --output=tar --outfd=1 -sy|tar tvf -
...
    self.tf = tarfile.open(None, 'w|', os.fdopen(output_fd, 'ab'))
...
OSError: [Errno 29] Illegal seek

The diff is tested by a unit test and manual testing with 2.7 & 3.6:
python2.7 ./xen-bugtool --output=tar --outfd=1 -sy|tar tvf -
python3.6 ./xen-bugtool --output=tar --outfd=1 -sy|tar tvf -

Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>